version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issues_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/issues_db
      SECRET_KEY: your-secret-key-change-in-production
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      UPLOAD_DIR: uploads
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: ./backend
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./backend/app:/app/app
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/issues_db
      SECRET_KEY: your-secret-key-change-in-production
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      UPLOAD_DIR: uploads
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
  redis_data: 